version: '3.8'

services:
  app:
    build: .
    container_name: recipe_app
    tty: true # for ruby inline debugging
    stdin_open: true # for ruby inline debugging
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: development
    command: bundle exec puma -C config/puma.rb

  db:
    image: postgres:13
    container_name: recipe-postgres-container
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
            POSTGRES_PASSWORD: postgres
volumes:
  postgres-data:
